// SPDX-License-Identifier: Apache-2.0
import type { PolicyEngine, State } from "@oxdeai/core";
import type { OxDeAIGuardConfig } from "@oxdeai/guard";

/**
 * An OpenAI Agents SDK tool call.
 *
 * Structurally compatible with the tool call shape produced by the OpenAI
 * Agents SDK - no import from that package is required.
 *
 * Key differences from LangGraph:
 *   - `input`   (not `args`)    - parsed tool arguments from the model
 *   - `call_id` (not `id`)      - tool call identifier generated by the model
 */
export type OpenAIAgentsToolCall = {
  /** Tool name - matches the function name registered with the agent. */
  name: string;
  /** Parsed tool arguments - matches the `input` field of an OpenAI Agents SDK ToolCall. */
  input: Record<string, unknown>;
  /** Tool call ID generated by the model - used as `intent_id`. */
  call_id?: string;
  /** Estimated monetary cost in whole units (e.g. USD). Passed to the default normalizer as `estimatedCost`. */
  estimatedCost?: number;
  /** Resource type hint (e.g. `"gpu"`, `"payment"`). Used to infer `action_type` by the default normalizer. */
  resourceType?: string;
  /** Unix timestamp in seconds. Defaults to `Date.now() / 1000` when absent. */
  timestampSeconds?: number;
};

/**
 * Configuration for `createOpenAIAgentsGuard`.
 *
 * Extends `OxDeAIGuardConfig` with a required `agentId` field.
 * OpenAI Agents SDK tool calls do not carry agent identity - the adapter
 * injects it from this config into every `ProposedAction` it builds.
 */
export type OpenAIAgentsGuardConfig = {
  /** The PolicyEngine instance that evaluates intent policy. */
  engine: PolicyEngine;
  /** Load the current policy state. May be async. */
  getState: () => State | Promise<State>;
  /** Persist the next state after a successful execution. May be async. */
  setState: (state: State) => void | Promise<void>;

  /**
   * Identity of the acting agent. Injected as `context.agent_id` on every
   * `ProposedAction` derived from a tool call.
   */
  agentId: string;

  /**
   * Optional custom mapping from a `ProposedAction` (built from the tool call)
   * to an OxDeAI `Intent`. When omitted, the guard's default normalizer is used.
   *
   * The `ProposedAction` passed here always has:
   *   - `name`    from `toolCall.name`
   *   - `args`    from `toolCall.input`
   *   - `context.agent_id`   from `config.agentId`
   *   - `context.intent_id`  from `toolCall.call_id` (when present)
   *   - `estimatedCost`      from `toolCall.estimatedCost`
   *   - `resourceType`       from `toolCall.resourceType`
   *   - `timestampSeconds`   from `toolCall.timestampSeconds` (or now)
   */
  mapActionToIntent?: OxDeAIGuardConfig["mapActionToIntent"];

  /** Called after authorization succeeds but before the execute callback. */
  beforeExecute?: OxDeAIGuardConfig["beforeExecute"];

  /**
   * Audit hook fired after every decision (ALLOW and DENY).
   * Errors thrown here are swallowed.
   */
  onDecision?: OxDeAIGuardConfig["onDecision"];

  /** When true, missing optional normalizer fields cause hard failures. */
  strict?: boolean;
};

/**
 * The guard function returned by `createOpenAIAgentsGuard`.
 * Call it with an OpenAI Agents SDK tool call and the execute callback.
 */
export type OpenAIAgentsGuardFn = <T>(
  toolCall: OpenAIAgentsToolCall,
  execute: () => Promise<T>
) => Promise<T>;
