import type { PolicyEngine, State } from "@oxdeai/core";
import type { OxDeAIGuardConfig, ProposedAction } from "@oxdeai/guard";

/**
 * A LangGraph / LangChain tool call.
 *
 * Structurally compatible with the `ToolCall` type from `@langchain/langgraph`
 * and `@langchain/core` - no import from those packages is required.
 * The optional OxDeAI fields (`estimatedCost`, `resourceType`, `timestampSeconds`)
 * can be attached when the tool call is constructed by the agent node.
 */
export type LangGraphToolCall = {
  /** Tool name - matches the `name` field of a LangChain ToolCall. */
  name: string;
  /** Tool arguments - matches the `args` field of a LangChain ToolCall. */
  args: Record<string, unknown>;
  /** Tool call ID generated by the LLM - used as `intent_id`. */
  id?: string;
  /** LangChain ToolCall type discriminant (`"tool_call"`). */
  type?: "tool_call";
  /** Estimated monetary cost in whole units (e.g. USD). Passed to the default normalizer as `estimatedCost`. */
  estimatedCost?: number;
  /** Resource type hint (e.g. `"gpu"`, `"payment"`). Used to infer `action_type` by the default normalizer. */
  resourceType?: string;
  /** Unix timestamp in seconds. Defaults to `Date.now() / 1000` when absent. */
  timestampSeconds?: number;
};

/**
 * Configuration for `createLangGraphGuard`.
 *
 * Extends `OxDeAIGuardConfig` with a required `agentId` field.
 * LangGraph tool calls do not carry agent identity - the adapter injects it
 * from this config into every `ProposedAction` it builds.
 */
export type LangGraphGuardConfig = {
  /** The PolicyEngine instance that evaluates intent policy. */
  engine: PolicyEngine;
  /** Load the current policy state. May be async. */
  getState: () => State | Promise<State>;
  /** Persist the next state after a successful execution. May be async. */
  setState: (state: State) => void | Promise<void>;

  /**
   * Identity of the acting agent. Injected as `context.agent_id` on every
   * `ProposedAction` derived from a tool call.
   */
  agentId: string;

  /**
   * Optional custom mapping from a `ProposedAction` (built from the tool call)
   * to an OxDeAI `Intent`. When omitted, the guard's default normalizer is used.
   *
   * The `ProposedAction` passed here always has:
   *   - `name`    from `toolCall.name`
   *   - `args`    from `toolCall.args`
   *   - `context.agent_id`   from `config.agentId`
   *   - `context.intent_id`  from `toolCall.id` (when present)
   *   - `estimatedCost`      from `toolCall.estimatedCost`
   *   - `resourceType`       from `toolCall.resourceType`
   *   - `timestampSeconds`   from `toolCall.timestampSeconds` (or now)
   */
  mapActionToIntent?: OxDeAIGuardConfig["mapActionToIntent"];

  /** Called after authorization succeeds but before the execute callback. */
  beforeExecute?: OxDeAIGuardConfig["beforeExecute"];

  /**
   * Audit hook fired after every decision (ALLOW and DENY).
   * Errors thrown here are swallowed.
   */
  onDecision?: OxDeAIGuardConfig["onDecision"];

  /** When true, missing optional normalizer fields cause hard failures. */
  strict?: boolean;
};

/**
 * The guard function returned by `createLangGraphGuard`.
 * Call it with a LangGraph tool call and the execute callback.
 */
export type LangGraphGuardFn = <T>(
  toolCall: LangGraphToolCall,
  execute: () => Promise<T>
) => Promise<T>;
